// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lQdvKq-A0vPQXS-6DL7bMkUA3eJRvU0',
    appId: '1:1045527091523:web:5db17955e367a7f84277f6',
    messagingSenderId: '1045527091523',
    projectId: 'apps-4e2fe',
    authDomain: 'apps-4e2fe.firebaseapp.com',
    storageBucket: 'apps-4e2fe.firebasestorage.app',
    measurementId: 'G-ERBRFXQNMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8aSg4kjvYPreZGwicIH_cuMmbH6QILlY',
    appId: '1:1045527091523:android:50d262e4a18bf5054277f6',
    messagingSenderId: '1045527091523',
    projectId: 'apps-4e2fe',
    storageBucket: 'apps-4e2fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBfxgG0ol3gPsVxyC-mjpPbA7s4b0VFy0',
    appId: '1:1045527091523:ios:63975463f8f4a2964277f6',
    messagingSenderId: '1045527091523',
    projectId: 'apps-4e2fe',
    storageBucket: 'apps-4e2fe.firebasestorage.app',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBfxgG0ol3gPsVxyC-mjpPbA7s4b0VFy0',
    appId: '1:1045527091523:ios:63975463f8f4a2964277f6',
    messagingSenderId: '1045527091523',
    projectId: 'apps-4e2fe',
    storageBucket: 'apps-4e2fe.firebasestorage.app',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8lQdvKq-A0vPQXS-6DL7bMkUA3eJRvU0',
    appId: '1:1045527091523:web:38ed8604dacec1104277f6',
    messagingSenderId: '1045527091523',
    projectId: 'apps-4e2fe',
    authDomain: 'apps-4e2fe.firebaseapp.com',
    storageBucket: 'apps-4e2fe.firebasestorage.app',
    measurementId: 'G-WQ4E3WNMSM',
  );
}
